-- District DPO directory + invite links (copy/paste into Supabase SQL editor)
--
-- What you get:
-- - district_dpo_directory: editable mapping of district -> DPO email
-- - dpo_invites + RPCs: create invite links, and accept invite links (creates an assessment row)
--
-- Notes:
-- - This migration assumes you already have the `assessments` table and the reporting-period columns migration applied.
-- - This migration uses a small `system_admins` table so you can control who can generate invites.

-- 1) Admin allow-list
create table if not exists system_admins (
  email text primary key
);

-- Add your admin emails here (edit as needed)
insert into system_admins(email)
values
  ('admin@foodsecurity.ug'),
  ('system.admin@kobbo.co'),
  ('aaronbaraka292@gmail.com')
on conflict do nothing;

create or replace function is_system_admin()
returns boolean
language sql
stable
as $$
  select exists(
    select 1
    from system_admins
    where lower(email) = lower(auth.jwt() ->> 'email')
  );
$$;

-- 2) District directory (simple text PK for now)
create table if not exists district_dpo_directory (
  district text primary key,
  email text not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_by uuid references auth.users
);

alter table district_dpo_directory enable row level security;

-- Make policy creation idempotent
drop policy if exists "Admins manage DPO directory" on district_dpo_directory;

create policy "Admins manage DPO directory"
  on district_dpo_directory for all
  using (is_system_admin())
  with check (is_system_admin());

-- 3) District link tokens (admin creates one link per district/period)
create table if not exists district_links (
  id bigint generated by default as identity primary key,
  district text not null,
  reporting_frequency text not null default 'biannual',
  reporting_year integer not null,
  reporting_period text not null,
  token text unique not null,
  status text not null default 'active', -- active | revoked
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table district_links enable row level security;

-- Make policies idempotent
drop policy if exists "Admins can manage district links" on district_links;
drop policy if exists "Authenticated can read district links" on district_links;

-- Admins can do everything (insert/update/delete)
create policy "Admins can manage district links"
  on district_links for all
  using (is_system_admin())
  with check (is_system_admin());

-- Any authenticated user can read links (needed by open_district_link RPC)
create policy "Authenticated can read district links"
  on district_links for select
  using (auth.role() = 'authenticated');

-- 4) Email queue for district invite links (so you can send via Resend / external worker)
create table if not exists district_invite_emails (
  id bigint generated by default as identity primary key,
  district text not null,
  email text not null,
  link_token text not null,
  link_url text not null,
  subject text not null,
  body text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  sent_at timestamp with time zone
);

-- Ensure reporting period columns exist for tracking invite coverage
alter table district_invite_emails
  add column if not exists reporting_year integer,
  add column if not exists reporting_period text,
  add column if not exists reporting_frequency text;

alter table district_invite_emails enable row level security;

drop policy if exists "Admins manage district invite emails" on district_invite_emails;

create policy "Admins manage district invite emails"
  on district_invite_emails for all
  using (is_system_admin())
  with check (is_system_admin());

-- 5) Relax assessments RLS so any authenticated user can edit (access controlled via unguessable links)
drop policy if exists "Users can view/edit their own assessments" on assessments;

-- Make new assessments policy idempotent
drop policy if exists "Authenticated can view/edit assessments" on assessments;

create policy "Authenticated can view/edit assessments"
  on assessments for all
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- 6) RPC: Ensure assessment + link for a district (admin)
-- - Upserts DPO email into directory
-- - Ensures an assessments row exists for (district, year, period, frequency)
-- - Ensures a stable token in district_links and returns it
drop function if exists ensure_district_link(text, text, integer, text, text);

create or replace function ensure_district_link(
  p_district_name text,
  p_dpo_email text,
  p_reporting_year integer,
  p_reporting_period text,
  p_reporting_frequency text default 'biannual'
)
returns table(token text)
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_link district_links%rowtype;
  existing_assessment assessments%rowtype;
  t text;
begin
  if not is_system_admin() then
    raise exception 'Not authorized';
  end if;

  -- Upsert directory entry (for record + email convenience)
  insert into district_dpo_directory(district, email, updated_by)
    values (p_district_name, p_dpo_email, auth.uid())
  on conflict (district) do update
    set email = excluded.email,
        updated_at = timezone('utc'::text, now()),
        updated_by = auth.uid();

  -- Ensure assessment exists for this district/period
  select *
    into existing_assessment
  from assessments a
  where a.district = p_district_name
    and a.reporting_year = p_reporting_year
    and a.reporting_period = p_reporting_period
    and a.reporting_frequency = p_reporting_frequency
  limit 1;

  if existing_assessment.id is null then
    insert into assessments(
      user_id,
      district,
      submission_data,
      status,
      reporting_year,
      reporting_period,
      reporting_frequency
    )
    values (
      auth.uid(),
      p_district_name,
      jsonb_build_object('district', p_district_name),
      'draft',
      p_reporting_year,
      p_reporting_period,
      p_reporting_frequency
    )
    returning * into existing_assessment;
  end if;

  -- Ensure a stable link token (use md5 over random + timestamp + user as a simple, unique-enough token)
  select *
    into existing_link
  from district_links dl
  where dl.district = p_district_name
    and dl.reporting_year = p_reporting_year
    and dl.reporting_period = p_reporting_period
    and dl.reporting_frequency = p_reporting_frequency
  limit 1;

  if existing_link.id is null then
    t := md5(random()::text || ':' || clock_timestamp()::text || ':' || coalesce(auth.uid()::text, 'anon'));
    insert into district_links(
      district,
      reporting_year,
      reporting_period,
      reporting_frequency,
      token,
      status
    )
    values (
      p_district_name,
      p_reporting_year,
      p_reporting_period,
      p_reporting_frequency,
      t,
      'active'
    )
    returning * into existing_link;
  end if;

  return query select existing_link.token;
end;
$$;

revoke all on function ensure_district_link(text, text, integer, text, text) from public;
grant execute on function ensure_district_link(text, text, integer, text, text) to authenticated;

-- 7) RPC: Queue an invite email for a district link (admin)
-- This:
-- - Ensures the district link exists (via ensure_district_link)
-- - Builds the full URL using a frontend-provided base URL
-- - Inserts a row into district_invite_emails for your email worker / Resend integration
drop function if exists queue_district_invite_email(text, text, text, integer, text, text);

create or replace function queue_district_invite_email(
  p_district_name text,
  p_dpo_email text,
  p_base_url text,
  p_reporting_year integer,
  p_reporting_period text,
  p_reporting_frequency text default 'biannual'
)
returns table(token text, link_url text)
language plpgsql
security definer
set search_path = public
as $$
declare
  t text;
  full_url text;
begin
  if not is_system_admin() then
    raise exception 'Not authorized';
  end if;

  -- Ensure link exists and get token
  select token
    into t
  from ensure_district_link(
    p_district_name,
    p_dpo_email,
    p_reporting_year,
    p_reporting_period,
    p_reporting_frequency
  );

  if t is null then
    raise exception 'Failed to generate district link';
  end if;

  full_url := rtrim(p_base_url, '/') || '/district-link?token=' || t;

  insert into district_invite_emails(
    district,
    email,
    link_token,
    link_url,
    subject,
    body,
    reporting_year,
    reporting_period,
    reporting_frequency
  )
  values (
    p_district_name,
    p_dpo_email,
    t,
    full_url,
    format('Food Security Assessment invite for %s district', p_district_name),
    format(
'Dear officer,

You have been invited to complete the Rapid Food and Nutrition Security Assessment for %s district, reporting period %s %s.

Please open the link below (or copy it into your browser) to access the assessment form:

%s

If you were not expecting this invitation, you can ignore this email.

Best regards,
MAAIF Food Security Team',
      p_district_name,
      p_reporting_year::text,
      p_reporting_period,
      full_url
    ),
    p_reporting_year,
    p_reporting_period,
    p_reporting_frequency
  );

  return query select t, full_url;
end;
$$;

revoke all on function queue_district_invite_email(text, text, text, integer, text, text) from public;
grant execute on function queue_district_invite_email(text, text, text, integer, text, text) to authenticated;

-- 8) View: per-district invite status (for admin dashboard follow-up)
-- Aggregates how many invites have been queued per district/period and when the last one was created.
create or replace view district_invite_status as
select
  district,
  reporting_year,
  reporting_period,
  reporting_frequency,
  max(created_at) as last_invited_at,
  count(*) as invites_count
from district_invite_emails
group by
  district,
  reporting_year,
  reporting_period,
  reporting_frequency;

-- 9) RPC: Open district link (used by frontend when visiting /district-link?token=...)
-- Returns the matching assessment id and basic period metadata.
drop function if exists open_district_link(text);

create or replace function open_district_link(link_token text)
returns table(
  assessment_id bigint,
  district text,
  reporting_year integer,
  reporting_period text,
  reporting_frequency text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  l district_links%rowtype;
  a assessments%rowtype;
begin
  select *
    into l
  from district_links
  where token = link_token
    and status = 'active'
  limit 1;

  if l.id is null then
    raise exception 'Invalid or revoked link';
  end if;

  select *
    into a
  from assessments
  where district = l.district
    and reporting_year = l.reporting_year
    and reporting_period = l.reporting_period
    and reporting_frequency = l.reporting_frequency
  limit 1;

  if a.id is null then
    raise exception 'Assessment not found for this district/period';
  end if;

  return query
  select
    a.id as assessment_id,
    coalesce(a.district, l.district) as district,
    a.reporting_year,
    a.reporting_period,
    a.reporting_frequency;
end;
$$;

revoke all on function open_district_link(text) from public;
grant execute on function open_district_link(text) to authenticated;

