-- 1. Main Assessments Table
-- Stores the core form data. 'submission_data' is a JSONB column
-- that holds the entire form state flexibly.
create table assessments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null, -- The 'Owner' / District Officer
  district text,
  submission_data jsonb default '{}'::jsonb,
  status text default 'draft' -- 'draft', 'submitted'
);

-- 2. Collaborators Table
-- Links invited users (by email) to a specific assessment and section (role).
create table assessment_collaborators (
  id bigint generated by default as identity primary key,
  assessment_id bigint references assessments(id) on delete cascade not null,
  role text not null, -- e.g. 'crop', 'livestock', 'fisheries', 'markets'
  email text not null,
  status text default 'pending', -- 'pending', 'accepted'
  invited_by uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Notifications Table
-- Simple system for in-app alerts (invites, reminders).
create table notifications (
  id bigint generated by default as identity primary key,
  user_email text not null,
  message text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable Row Level Security (RLS)
-- This is crucial for security so users can only see their own data.
alter table assessments enable row level security;
alter table assessment_collaborators enable row level security;
alter table notifications enable row level security;

-- 5. RLS Policies

-- Assessments: Owners can do everything. Collaborators can VIEW/UPDATE based on ID.
create policy "Users can view/edit their own assessments"
  on assessments for all
  using (auth.uid() = user_id);

create policy "Collaborators can view assessments they are invited to"
  on assessments for select
  using (
    exists (
      select 1 from assessment_collaborators
      where assessment_id = assessments.id
      and email = auth.jwt() ->> 'email'
    )
  );

create policy "Collaborators can update assessments they are invited to"
  on assessments for update
  using (
    exists (
      select 1 from assessment_collaborators
      where assessment_id = assessments.id
      and email = auth.jwt() ->> 'email'
    )
  );

-- Collaborators Table: Users can see invites sent by them OR to them.
create policy "Users can view collaborators they invited"
  on assessment_collaborators for select
  using (auth.uid() = invited_by);

create policy "Users can see if they are a collaborator"
  on assessment_collaborators for select
  using (email = auth.jwt() ->> 'email');

create policy "Users can invite collaborators"
  on assessment_collaborators for insert
  with check (auth.uid() = invited_by);

-- Allow invitees to accept their invite (update their own row)
create policy "Invitees can accept their invite"
  on assessment_collaborators for update
  using (email = auth.jwt() ->> 'email')
  with check (email = auth.jwt() ->> 'email');

-- Allow inviters (owners) to delete invites/collaborators they created
create policy "Inviters can delete collaborators they invited"
  on assessment_collaborators for delete
  using (auth.uid() = invited_by);

-- Notifications: Users can only see their own notifications.
create policy "Users can see their own notifications"
  on notifications for select
  using (user_email = auth.jwt() ->> 'email');

create policy "System/Users can insert notifications"
  on notifications for insert
  with check (true); -- Allow inserts (usually triggered by backend logic or other users)
